//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Transactions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Transactions.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel more than once..
        /// </summary>
        internal static string CannotCancelMoreThanOnce {
            get {
                return ResourceManager.GetString("CannotCancelMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compensate more than once..
        /// </summary>
        internal static string CannotCompensateMoreThanOnce {
            get {
                return ResourceManager.GetString("CannotCompensateMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow already completed, cannot complete again..
        /// </summary>
        internal static string WorkflowAlreadyCompletedCannotCompleteAgain {
            get {
                return ResourceManager.GetString("WorkflowAlreadyCompletedCannotCompleteAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow already completed, cannot rollback..
        /// </summary>
        internal static string WorkflowAlreadyCompletedCannotRollback {
            get {
                return ResourceManager.GetString("WorkflowAlreadyCompletedCannotRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow disposed, cannot complete..
        /// </summary>
        internal static string WorkflowDisposedCannotComplete {
            get {
                return ResourceManager.GetString("WorkflowDisposedCannotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow disposed, cannot rollback..
        /// </summary>
        internal static string WorkflowDisposedCannotRollback {
            get {
                return ResourceManager.GetString("WorkflowDisposedCannotRollback", resourceCulture);
            }
        }
    }
}
